#! /usr/bin/ruby

# Copyright (c) 2016, Google Inc.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
# OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE. */

require 'digest'

# Two separate tests depend on the data produced here in different ways:
#
#  * crypto/hash_unittests.cc uses the fact that
#       |digest| = Hash(|in|)
#    to check the correctness of hash algorithms.
#
#  * common/stream_unittests.cc uses the fact that
#       |in[n]| = |digest[0]| + |digest[1]| + ... + |digest[n-1]|
#    to send n-1 digests resulting in a stream digest equaling |digest[n]|.

ALGS = {
  "sha256_tests.txt" => Digest::SHA256.new,
  "sha384_tests.txt" => Digest::SHA384.new,
}

# Main routine: Take self-signed certificates in <cert-dir> and use them to
# generate test data files in <test-dir>
if ARGV.length != 1
  puts "[-] usage: #{$0} <test-dir>"
  exit 1
end

# Truncate any existing test data files and add an informative header
tool = File.expand_path($0).gsub(/.*vapidssl\//, '')
date = Time.now.strftime("%m/%d/%Y")
Dir.chdir(ARGV[0]) do
  ALGS.each do |data_file, hash|
    File.open(data_file, 'w') do |f|
      f.puts "# This file was auto-generated by #{tool} on #{date}"
      f.puts
      # Generate a bunch of digests iteratively
      data = ''
      32.times do
        digest = hash.hexdigest(data)
        f.puts "IN: " + data.unpack('H*')[0]
        f.puts "DIGEST: " + digest
        f.puts
        data += hash.digest(data)
      end
    end
  end
end
